networks:
  dionaea_local:

services:
  # Dionaea service
  dionaea:
    build: .
    container_name: dionaea
    stdin_open: true
    tty: true
    restart: always
    #    cpu_count: 1
    #    cpus: 0.25
    networks:
      - dionaea_local
    ports:
      - "20:20"
      - "21:21"
      - "42:42"
      - "69:69/udp"
      - "81:81"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "3306:3306"
      #     - "5060:5060"
      #     - "5060:5060/udp"
      #     - "5061:5061"
      - "27017:27017"
    image: "khulnasoft/dionaea:24.04"
    read_only: true
    volumes:
      - $HOME/cyberpot/data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
      - $HOME/cyberpot/data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
      - $HOME/cyberpot/data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
      - $HOME/cyberpot/data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
      - $HOME/cyberpot/data/dionaea:/opt/dionaea/var/dionaea
      - $HOME/cyberpot/data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
      - $HOME/cyberpot/data/dionaea/log:/opt/dionaea/var/log
      - $HOME/cyberpot/data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp
