networks:
  ciscoasa_local:

services:
  # Ciscoasa service
  ciscoasa:
    build: .
    container_name: ciscoasa
    restart: always
    tmpfs:
      - /tmp/ciscoasa:uid=2000,gid=2000
    #    cpu_count: 1
    #    cpus: 0.25
    networks:
      - ciscoasa_local
    ports:
      - "5000:5000/udp"
      - "8443:8443"
    image: "khulnasoft/ciscoasa:24.04"
    read_only: true
    volumes:
      - $HOME/cyberpot/data/ciscoasa/log:/var/log/ciscoasa
