services:
  # glutton service
  glutton:
    build: .
    container_name: glutton
    restart: always
    tmpfs:
      - /var/lib/glutton:uid=2000,gid=2000
      - /run:uid=2000,gid=2000
    #    cpu_count: 1
    #    cpus: 0.75
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    image: "khulnasoft/glutton:24.04"
    read_only: true
    volumes:
      - $HOME/cyberpot/data/glutton/log:/var/log/glutton
      - $HOME/cyberpot/data/glutton/payloads:/opt/glutton/payloads
#     - $HOME/cyberpot/docker/glutton/dist/rules.yaml:/opt/glutton/config/rules.yaml
