services:
  # Fatt service
  fatt:
    build: .
    container_name: fatt
    restart: always
    #    cpu_count: 1
    #    cpus: 0.75
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    image: "khulnasoft/fatt:24.04"
    volumes:
      - $HOME/cyberpot/data/fatt/log:/opt/fatt/log
