services:
  # P0f service
  p0f:
    build: .
    container_name: p0f
    restart: always
    #    cpu_count: 1
    #    cpus: 0.75
    network_mode: "host"
    image: "khulnasoft/p0f:24.04"
    read_only: true
    volumes:
      - $HOME/cyberpot/data/p0f/log:/var/log/p0f
