networks:
  medpot_local:

services:
  # medpot service
  medpot:
    build: .
    container_name: medpot
    restart: always
    #    cpu_count: 1
    #    cpus: 0.25
    networks:
      - medpot_local
    ports:
      - "2575:2575"
    image: "khulnasoft/medpot:24.04"
    read_only: true
    volumes:
      - $HOME/cyberpot/data/medpot/log/:/var/log/medpot
